### ISSUE TITLE
error: 'PubSubClient ESPHelper::client' is private

### ISSUE THREAD

**Issue by washichi** [ItKindaWorks/ESPHelper#10]
If this is an failure because of my lack of knowledge I apologize in advance.

I tried to run the [relayControl](https://github.com/ItKindaWorks/ESPHelper/tree/master/examples/relayControl) example, but I get this error:

```
In file included from C:\Users\.....\Documents\Projects\Arduino\IOThing_D1\IOThing_D1.ino:25:0:

C:\Users\.....\Documents\Arduino\libraries\ESPHelper\src/ESPHelper.h: In function 'void callback(char*, byte*, unsigned int)':

C:\Users\.....\Documents\Arduino\libraries\ESPHelper\src/ESPHelper.h:166:15: error: 'PubSubClient ESPHelper::client' is private

  PubSubClient client;

               ^

IOThing_D1:93: error: within this context

     myESP.client.publish(statusTopic, "0", true);

           ^

exit status 1
within this context
```

-------------
I Installed the pubsub library (today) via the library manager. (also installed metro library)

Line 25: `#include "ESPHelper.h`
Line 93: `myESP.client.publish(statusTopic, "0", true);`

tested boards: [D1 mini](https://www.aliexpress.com/store/product/D1-mini-Mini-NodeMcu-4M-bytes-Lua-WIFI-Internet-of-Things-development-board-based-ESP8266/111482_32687916072.html)
NodeMCU v3 LOLin

**Comment by narfel** [comment]
You probably solved that by now, but if not make sure you are on version 2.6.0 or higher of PubSubClient. I remember vaguely having the same problem in a different context and was running an outdated version.

**Comment by washichi** [comment]
I don't think that was the problem since I checked for updates., however I solved it by starting with the RelayControlV2 and stripping it down to basic. If anyone has the same issue I can look into what caused it, but for now I'm happy it's all working, and I can use your awesome ESPHelper library :)
