### ISSUE TITLE
Small features

### ISSUE THREAD

**Issue by PitySOFT** [ItKindaWorks/ESPHelper#14]
Hi,

Thank you for this library I love It. When you have time please add:

1. callback for when the WiFi get disconnected
2. custom heartbeat time (I see that now is set on 1 second)
3. a led status for when the device is trying to connect (If you have multiple networks it takes a few seconds till connects to the one that is available and the led is off)
4. add QOS to publish method so I can specify for each publish what QOS I want.
5. maybe you can use this [MQTT library](https://github.com/Imroy/pubsubclient). I think it's much cleaner to work with it.

**Comment by ItKindaWorks** [comment]
Hi pitySOFT, thanks for your interest in ESPHelper!

I sort of thought I had implemented a disconnect callback but maybe it never ended up in the posted version. I seem to remember it clashing with the connect callback in the way the loop function worked. I'll look into that one again. 

On the issue of the heartbeat I could add a setter for that but I've also thought about just removing that functionality all together as well. One of the big struggles with a library like this is keeping things organized and not trying to create a god class which I think ESPHelper has grown into a bit.  Related to that is the status light for connecting; While I think both features are useful, I think some of those choices should be for the user of the library to decide or at least shouldn't be part of the core code of ESPHelpr. I may at some point break out the heartbeat (and other status lighting modes) functionality into a separate class that can be used in conjunction with ESPHelper but not a core part of it. Still thinking things over though. I'll keep a custom time setting in mind while I think about what to do with the heartbeat function though...

While I would also like the ability to specify outgoing QOS and that other library has been pointed out to me before, I prefer the one from knolleary as it is the one most people will already have or will end up downloading (it comprises the top 10 or so results on google when googling pubsubclient). If that library ends up adding in publish QOS support then I will be more than happy to add it in but until that version of the library supports it I'd rather not go down that path.

**Comment by japamar** [comment]
Hi,

It would be nice the possibility to set the MQTT "Topic" in the config page.

Thanks.

**Comment by debsahu** [comment]
@ItKindaWorks Great work here.

To implement wifi connect/disconnect event you could add these code:
```
WiFiEventHandler wifiConnectHandler;
WiFiEventHandler wifiDisconnectHandler;
```
In setup(), in your case myESP.begin()
```
  wifiConnectHandler = WiFi.onStationModeGotIP(onWifiConnect); // callback function is onWiFiConnect
  wifiDisconnectHandler = WiFi.onStationModeDisconnected(onWifiDisconnect); // callback function is onWiFiDisconnect
```

Took ***directly*** from https://github.com/marvinroger/async-mqtt-client/blob/master/examples/FullyFeatured-ESP8266/FullyFeatured-ESP8266.ino

**Comment by debsahu** [comment]
On a similar topic regarding MQTT, any thoughts of migrating to Async MQTT implementation?  https://github.com/marvinroger/async-mqtt-client

**Comment by ItKindaWorks** [comment]
I'm going to close this topic as there are too many little features being discussed and I'd rather have each feature broken out into it's own topic for discussion. I'm not trying to steamroll any ideas but I want to have those discussions be separated.

As of right now, wifi disconnect callback has been implemented though I may end up re-doing all of the callback handling to be more in line with @debsahu comments above (thanks!)

For MQTT I'm going to keep with the knolleary pubsubclient (https://github.com/knolleary/pubsubclient) as that is the most popular mqtt client. As features end up in that lib I am happy to add them into ESPHelper if/when it makes sense.
