### ISSUE TITLE
MQTT over TLS 

### ISSUE THREAD

**Issue by ankycooper** [ItKindaWorks/ESPHelper#16]
Hi, 
Firstly thanks a ton for the Library, you have done an amazing job. 
Just a quick one MQTT over TLS supported?
 if yes could you please provide an example?
 if no any plans or ETA on your roadmap?

Cant convince my brain to use unencrypted mqtt? All brokers and other devices use encrypted.
 
one again thanks a lot for all the hardwork!!

**Comment by ankycooper** [comment]
Sorry my bad found the example of secure mqtt. works well except 1 issue.

I use letsencrypt certs, which expires every 90 days, I don't want to re-upload code to all devices every time cert changes. I tried using ca cert in the sha1 fingerprint, with that I can publish, but but the subscribe callback is not called.

I'm thinking of publishing it via a webserver and the then esp picks it during setup phase. let me know if you can think of a better way.

**Comment by ItKindaWorks** [comment]
You could always store the cert in a config file that is loaded at startup. Then you just go in and update the cert every once in a while and trigger a restart. It could even do this automatically from a computer/server side script that pushes the cert via mqtt or some other protocol.
