### ISSUE TITLE
esphelper error No Answer to our Authentication

### ISSUE THREAD

**Issue by SteveRMann** [ItKindaWorks/ESPHelper#17]
I have several esp devices around the house, and the Arduino sketch is essentially similar except for the nodename and connectname.  I can upload to any of them except one.  In that case (a Sonoff Switch), I get this error:
esphelper error No Answer to our Authentication

Early in my sketch I define the nodename:
#define NODENAME "counter"

And in my setup()
```
  //espHelper
  myESP.OTA_enable();
  myESP.OTA_setPassword(NODENAME);
  myESP.OTA_setHostname(NODENAME);
  myESP.begin();
```
I am pretty certain that espHelper is running because I see the hostname in the IDE Port: dropdown, and with the correct IP.

I have two other Sonoff switches and they are also running the same code _except_ NODENAME is different for each of them.  I even tried loading 'counter.ino' through the com port on a different Sonoff Switch- same results.  I restart the IDE and the node "counter" is in the Port list, but I still get the same error.

Any help you could offer would be appreciated.

[counter.ino.txt](https://github.com/ItKindaWorks/ESPHelper/files/1705769/counter.ino.txt)

**Comment by jaromanda** [comment]
Your code actually does

`//espHelper`
 `myESP.OTA_enable();`
  `myESP.OTA_setPassword("NODENAME");` - note the " here
  `myESP.OTA_setHostname(NODENAME);`
  `myESP.begin();`

So the OTA password is **NODENAME**, not **counter**

**Comment by SteveRMann** [comment]
Not the problem.  I quoted NODENAME in an attempt to make sure the 
problem wasn't in the #define, and forgot to unquote it before posting.
Even with an explicit password, I still can't get this esp to load OTA.

Any other tips?
Are there any IDE parameters that could affect this?

Thanks,
Steve Mann

**Comment by jaromanda** [comment]
OK, just making sure. So, it's only an issue when the node name is "counter"?

**Comment by frownbreaker** [comment]
Just a quick question; the Sonoff unit it an ESP8266 based unit or an ESP8265?

I ask as I have several ESP2866 boards that OTA fine but I have one ESP8265 (Wemos D1 mini lite) that gives me an OTA Error. You say you only have one device with a problem with OTA the recent Sonoffs like the slampher v2 use the ESP8265.

I've just tried this: 

My program that works fine OTA on 

- A) Wemos D1 Mini -Based on ESP8266 4megs flash
- B) [Wemos D1 Mini Lite - Based on ESP8265 1meg flash ](https://wiki.wemos.cc/products:d1:d1_mini_lite)

The same code works fine on A) and fails on the B) "error No Answer to our Authentication" it might be a space issue as the ESP8265 only has 1mb of flash and OTA needs more space?

My program is small and uses 34%


```
Archiving built core (caching) in: \arduino_cache_670130\core\core_esp8266_esp8266_d1_mini_lite_CpuFrequency_80,FlashSize_1M0,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,FlashErase_none,UploadSpeed_921600_38f8d60c80832e1af84c0c83dd0f067b.a
Sketch uses 349789 bytes (34%) of program storage space. Maximum is 1023984 bytes.
Global variables use 36976 bytes (45%) of dynamic memory, leaving 44944 bytes for local variables. Maximum is 81920 bytes.
AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.13/esptool.exe -vv -cd nodemcu -cb 921600 -cp COM3 -ca 0x00000 -cf AppData\Local\Temp\arduino_build_508794/BedSharpProxSensor.ino.bin 
esptool v0.4.13 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to nodemcu
	setting baudrate from 115200 to 921600
	setting port from COM1 to COM3
	setting address from 0x00000000 to 0x00000000
	espcomm_upload_file
	espcomm_upload_mem
	setting serial port timeouts to 1000 ms
opening bootloader
resetting board
```

This is the full error when attempting an OTA

```
Archiving built core (caching) in: \Temp\arduino_cache_670130\core\core_esp8266_esp8266_d1_mini_lite_CpuFrequency_80,FlashSize_1M0,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,FlashErase_none,UploadSpeed_921600_38f8d60c80832e1af84c0c83dd0f067b.a
Sketch uses 349789 bytes (34%) of program storage space. Maximum is 1023984 bytes.
Global variables use 36976 bytes (45%) of dynamic memory, leaving 44944 bytes for local variables. Maximum is 81920 bytes.
python.exe C:\Users\seth\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1/tools/espota.py -i 192.168.0.236 -p 8266 --auth=1234 -f C:\Users\seth\AppData\Local\Temp\arduino_build_508794/BedSharpProxSensor.ino.bin 
Authenticating...Exception in thread "Timer-0" java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at cc.arduino.packages.discoverers.network.BoardReachabilityFilter.run(BoardReachabilityFilter.java:63)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
FAIL
00:31:30 [ERROR]: No Answer to our Authentication
```

**Comment by ghost** [comment]
Did you find a solution to this? I have a similar issue.

It works for multiple ESP8266 12E modules as well WeMos D1 and D1 mini without any problems.
But it doesn't work on ESP8266 01.

I get:
 "Authenticating...FAIL
03:46:31 [ERROR]: No Answer to our Authentication"

**Comment by SteveRMann** [comment]
I haven't readdressed this specific problem- too many other irons in the fire.
On the -01 you absolutely must be using the 1Mb model.  OTA will not work on the original 512Kb model.  Also, when compiling, you absolutely cannot use more than 49% or the RAM, or OTA just won't work.

**Comment by ghost** [comment]
Yeah, I figured it out eventually. My ESP 01s are apparently the 512k model.

Thanks for your reply!

**Comment by terrag42** [comment]
Thanks for your reply StevRMann and ghost! Incorrect flash size selection was my problem as well.
