### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by jeffeb3** [ItKindaWorks/ESPHelper#2]
I see there are some compiler warnings, about sending string constants as char*'s. I think this is an easy fix, just using "const char *" instead.

Not a big deal, but might be a useful issue to have, when you feel like fixing it.

**Comment by ItKindaWorks** [comment]
Thanks! I'll try to get those sorted out in a future commit! I cant remember atm why I used char* instead of const char* but doing that was just a band-aid fix and not a real fix to whatever the underlying issue was. Should be easy enough to fix the correct way though.

**Comment by ItKindaWorks** [comment]
Most of these issues should be resolved by the latest commit.
