### ISSUE TITLE
Wifi connection get lost consistantly when i start mqtt server on rpi

### ISSUE THREAD

**Issue by sanjayrajatnahata** [ItKindaWorks/ESPHelper#30]
Hi
I am using esphelper library in my project which is using pir sensor which lights up the bulb 
When I use esphelper till wifi connection it's OK when I start raspberry pi which runs mqtt server the connection to wifi gets lost and ip is unset and set again at regular intervals  (mostly within 15 Sec or so)

**Comment by ItKindaWorks** [comment]
Hmm, thats a new one I haven't run into before. Can you possibly post the code that you are using that causes this error?

**Comment by sanjayrajatnahata** [comment]
Please find the code file attached
[KitchenStore.txt](https://github.com/ItKindaWorks/ESPHelper/files/3100002/KitchenStore.txt)

**Comment by sanjayrajatnahata** [comment]
Please find the code file attached
[KitchenStore.txt](https://github.com/ItKindaWorks/ESPHelper/files/3100002/KitchenStore.txt)

**Comment by uherting** [comment]
@sanjayrajatnahata : What is the point in commenting out the line "myESP.loop();"? Maybe your intention was to comment out the line before / after "myESP.loop();" by using double slashes? Just an idea...

**Comment by sanjayrajatnahata** [comment]
There is no problem in library
the problem was the analogRead in esp8266 nodemcu 
so I am closing this thread
