### ISSUE TITLE
Fatel Error: Metro.h: No such file or directory

### ISSUE THREAD

**Issue by hb5fa** [ItKindaWorks/ESPHelper#8]
I got the Metro.h (No such file or directory error) when I first tried out ESPHelper basicUse project.  Any idea if the custom Metro.h file should be included into the project?

**Comment by ItKindaWorks** [comment]
Have you installed the Metro library from [here](https://www.pjrc.com/teensy/td_libs_Metro.html)?

**Comment by hb5fa** [comment]
Yes I did.  Now I am getting ESP8266mDNS.h error.  I do have pubsubclient library installed.

**Comment by ItKindaWorks** [comment]
Have you installed the ESP8266 core files from [here](https://github.com/esp8266/Arduino)?

**Comment by hb5fa** [comment]
Let me try.  I didn't see it in your instruction.

**Comment by hb5fa** [comment]
Imported the library.  Still getting the same error.  Let me try something different.

**Comment by hb5fa** [comment]
Giving up!  It forces me to use Teensy board.  Once I switched back to generic ESP8266 board, the same Metro.h missing error again.

**Comment by ItKindaWorks** [comment]
Where do you have the metro library installed? Is it in your libraries folder inside of your sketch folder? The Metro library shouldn't be only usable with teensy.

**Comment by hb5fa** [comment]
I used the installer.  I followed the instruction and installed in under the Arduino's un-zipped directory.

**Comment by hb5fa** [comment]
Arduino: 1.8.2 (Windows 10), TD: 1.36, Board: "Generic ESP8266 Module, 80 MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS), ck, Disabled, None"

In file included from D:\_AllProjects\ESP8266\ESPHelperBasic\ESPHelperBasic.ino:22:0:

E:\LocalLibraries\MyDocuments\Arduino\libraries\ESPHelper-master\src/ESPHelper.h:33:19: fatal error: Metro.h: No such file or directory

 #include "Metro.h"

                   ^

compilation terminated.

exit status 1
Error compiling for board Generic ESP8266 Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ItKindaWorks** [comment]
Download [this](https://github.com/thomasfredericks/Metro-Arduino-Wiring/archive/master.zip) and install the library into your Arduino sketches/libraries folder. Here is a guide on installing libraries manually https://www.arduino.cc/en/guide/libraries

**Comment by hb5fa** [comment]
Let me try

**Comment by hb5fa** [comment]
Specified folder/zip file does not contain a valid library
Specified folder/zip file does not contain a valid library

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by hb5fa** [comment]
That's when I tried to import the library as ZIP file.

**Comment by hb5fa** [comment]
Trying Manually now.

**Comment by ItKindaWorks** [comment]
unzip the folder and read the INSTALL.txt file within.

**Comment by hb5fa** [comment]
Ok.  Trying...

**Comment by hb5fa** [comment]
Looks like it's going now!!!  Thanks so much!  I can upload the initial sketch now.  I'll try the functionalities.

**Comment by ItKindaWorks** [comment]
Great to hear you got it working!
